# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gnJU_SZ5tVbI3ExmvooIbPdNA7Sk61tQ
"""

import pandas as pd

from util  import*
from cross_val_split import cross_val_split
from predict import predict_data

def timesfm_model():
  cus_obj=CustomData()
  window_size=cus_obj.window_size
  step_size=cus_obj.step_size
  data=cus_obj.read_file(cus_obj.data_path)
  # train_data, test_data, step_size=cross_val_split(data,cus_obj.window_size,cus_obj.step_size)
  predictions=predict_data(data,initial_window_size=500,step_size=14)
  data["predicted_fm"] = predictions
  data_select=data[~(data['predicted_fm'].isnull())]
  data_select['Error_rate']=(abs(data_select['y']-data_select['predicted_fm'])/data_select['y'])*100
  print("Mean Error Rate",data_select['Error_rate'].mean())
  return data_select

data_select=timesfm_model()

